openapi: 3.0.0
info:
  title: Kitap API
  version: 1.0.0
  description: CRUD operasyonlarını ve List metodunu sağlayan Kitap API'si

paths:
  /books:
    get:
      summary: Tüm kitapları listele
      operationId: listBooks
      responses:
        '200':
          description: Başarılı yanıt
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Yeni bir kitap oluştur
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Başarılı yanıt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{id}:
    get:
      summary: Belirli bir kitabı getir
      operationId: getBookById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Başarılı yanıt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Kitap bulunamadı
    put:
      summary: Belirli bir kitabı güncelle
      operationId: updateBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Başarılı yanıt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Kitap bulunamadı
    delete:
      summary: Belirli bir kitabı sil
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Başarılı yanıt
        '404':
          description: Kitap bulunamadı

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        year:
          type: integer
